# Generated by Django 4.2 on 2026-01-05 05:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=20)),
                ('amount_paid', models.IntegerField()),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
