# Generated by Django 4.2 on 2026-01-05 05:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=20)),
                ('amount_paid', models.IntegerField()),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.registration')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
