# Generated by Django 4.2 on 2026-01-03 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('quota', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('organizer_id', models.UUIDField()),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
