# Generated by Django 4.2 on 2026-01-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_start', models.DateTimeField()),
                ('sales_end', models.DateTimeField()),
                ('quota', models.IntegerField()),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
